name: Unit test

on: [push, pull_request]

jobs:
  unit_test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-18.04, windows-2016 ]
        node-version: [10.x, 12.x, 14.x, 15.x]

    env:
      EMAIL_VALIDATION_API_KEY: ${{ secrets.API_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run test
      run: |
        rm package-lock.json
        npm install --no-optional
        npm run test